[/Script/ShooterGame.ShooterGameMode]
bAllowFlyerSpeedLeveling=false
bAllowSpeedLeveling=true
bPvEAllowTribeWar=true
bPvEAllowTribeWarCancel=false
bUseSingleplayerSettings=false
ServerAutoForceRespawnWildDinosInterval=4
bAllowCustomRecipes=true
CustomRecipeEffectivenessMultiplier=1
CustomRecipeSkillMultiplier=1
bPassiveDefensesDamageRiderlessDinos=false
GlobalPoweredBatteryDurabilityDecreasePerSecond=4
bIncreasePvPRespawnInterval=true
IncreasePvPRespawnIntervalCheckPeriod=300
IncreasePvPRespawnIntervalMultiplier=2
IncreasePvPRespawnIntervalBaseAmount=60
ResourceNoReplenishRadiusPlayers=1.000000
ResourceNoReplenishRadiusStructures=1.000000
GlobalSpoilingTimeMultiplier=0.500000
GlobalItemDecompositionTimeMultiplier=1.000000
GlobalCorpseDecompositionTimeMultiplier=1.000000
UseCorpseLifeSpanMultiplier=1.000000
CropGrowthSpeedMultiplier=2.000000
CropDecaySpeedMultiplier=2.000000
PoopIntervalMultiplier=1.500000
DinoHarvestingDamageMultiplier=1.00
PlayerHarvestingDamageMultiplier=1.00
DinoTurretDamageMultiplier=1.00
BabyFoodConsumptionSpeedMultiplier=1.00
bUseCorpseLocator=true
bAllowPlatformSaddleMultiFloors=true
bAllowUnlimitedRespecs=true
bDisableStructurePlacementCollision=true
SupplyCrateLootQualityMultiplier=2.50
FishingLootQualityMultiplier=2.50
CraftingSkillBonusMultiplier=2.00
bAutoUnlockAllEngrams=true

LayEggIntervalMultiplier=7
MatingIntervalMultiplier=0.001
MatingSpeedMultiplier=5
EggHatchSpeedMultiplier=30
BabyMatureSpeedMultiplier=300
BabyImprintingStatScaleMultiplier=3
BabyImprintAmountMultiplier=3
BabyCuddleIntervalMultiplier=0.01
BabyCuddleGracePeriodMultiplier=0.1
BabyCuddleLoseImprintQualitySpeedMultiplier=2

MaxNumberOfPlayersInTribe=6
bAutoPvETimer=false
bGenesisUseStructuresPreventionVolumes=True
StructureDamageRepairCoolDown=180
FuelConsumptionIntervalMultiplier=1.00
bDisableFriendlyFire=false
bDisableDinoRiding=false
bDisableDinoTaming=false
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
KillXPMultiplier=15
CraftXPMultiplier=10
HarvestXPMultiplier=5
GenericXPMultiplier=1
SpecialXPMultiplier=1
ExplorerNoteXPMultiplier=0.75
BossKillXPMultiplier=20
AlphaKillXPMultiplier=5
WildKillXPMultiplier=10
CaveKillXPMultiplier=10
TamedKillXPMultiplier=15
UnclaimedKillXPMultiplier=0.01
PlayerBaseStatMultipliers[0]=1.00 # Health - Base is 100
PlayerBaseStatMultipliers[1]=1.00 # Stamina - Base is 100
PlayerBaseStatMultipliers[2]=1.00 # Torpidity - Base is 100
PlayerBaseStatMultipliers[3]=1.00 # Oxygen - Base is 150
PlayerBaseStatMultipliers[4]=1.00 # Food - Base is 100
PlayerBaseStatMultipliers[5]=1.00 # Water - Base is 100
PlayerBaseStatMultipliers[6]=1.00 # Unused stat (temperature)
PlayerBaseStatMultipliers[7]=1.00 # Weight - Base is 100
PlayerBaseStatMultipliers[8]=1.00 # Melee Damage (Base cannot be increased) - Base is 100%
PlayerBaseStatMultipliers[9]=1.00 #Speed (Base cannot be increased) - Base is 100%
PlayerBaseStatMultipliers[10]=1.00 #Temperature Fortitude (Base cannot be increased) - Base is 100%
PlayerBaseStatMultipliers[11]=1.00 #Crafting Skill (Base cannot be increased) - Base is 0
PerLevelStatsMultiplier_Player[0]=3.25 # Health - Base increase is 10
PerLevelStatsMultiplier_Player[1]=2.25 # Stamina - Base increase is 10
PerLevelStatsMultiplier_Player[3]=1.25 # Oxygen - Base increase is 20
PerLevelStatsMultiplier_Player[4]=3.50 # Food - Base increase is 10
PerLevelStatsMultiplier_Player[5]=3.50 # Water - Base increase is 10
PerLevelStatsMultiplier_Player[6]=1.00 # Unused Stat (temperature)
PerLevelStatsMultiplier_Player[7]=10.25 # Weight - Base increase is 10
PerLevelStatsMultiplier_Player[8]=2.75 # Melee Damage - Base increase is 5%
PerLevelStatsMultiplier_Player[9]=3.25 # Speed - Base increase is 1.5%
PerLevelStatsMultiplier_Player[10]=3.50 # Temperature Fortitude - Base increase is 2
PerLevelStatsMultiplier_Player[11]=1.5 # Crafting Skill - Base increase is 10%
PerLevelStatsMultiplier_DinoTamed[0]=0.50 # Health - Default is 0.20
PerLevelStatsMultiplier_DinoTamed[1]=1.75 # Stamina - Default is 1.00
PerLevelStatsMultiplier_DinoTamed[3]=1.50 # Oxygen - Default is 1.00
PerLevelStatsMultiplier_DinoTamed[4]=1.50 # Food - Default is 1.00
PerLevelStatsMultiplier_DinoTamed[7]=8.50 # Weight - Default is 1.00
PerLevelStatsMultiplier_DinoTamed[8]=0.75 # Melee Damage - Default is 0.17
PerLevelStatsMultiplier_DinoTamed[9]=1.5 # Speed - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Add[0]=2.0 # Health - Default is 0.14
PerLevelStatsMultiplier_DinoTamed_Add[1]=2.0 # Stamina - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Add[3]=1.0 # Oxygen - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Add[4]=1.0 # Food - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Add[7]=4.0 # Weight - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Add[8]=2.0 # Melee Damage - Default is 0.14
PerLevelStatsMultiplier_DinoTamed_Add[9]=2.0 # Speed - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.44 # Health - Default is 0.44
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1.00 # Stamina - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1.00 # Oxygen - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1.00 # Food - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Affinity[7]=1.00 # Weight - Default is 1.00
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.44 # Melee Damage - Default is 0.44
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1.00 # Speed - Default is 1.00
PerLevelStatsMultiplier_DinoWild[0]=1.00 # Health - Default is 1.00
PerLevelStatsMultiplier_DinoWild[1]=1.00 # Stamina - Default is 1.00
PerLevelStatsMultiplier_DinoWild[3]=1.00 # Oxygen - Default is 1.00
PerLevelStatsMultiplier_DinoWild[4]=1.00 # Food - Default is 1.00
PerLevelStatsMultiplier_DinoWild[6]=1.00 # Unused Stat (temperature) - Default is 1.00
PerLevelStatsMultiplier_DinoWild[7]=1.00 # Weight - Default is 1.00
PerLevelStatsMultiplier_DinoWild[8]=1.00 # Melee Damage - Default is 1.00
PerLevelStatsMultiplier_DinoWild[9]=1.00 # Speed - Default is 1.00
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawMeat_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawPrimeMeat_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawMeat_Fish_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Chitin_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Metal_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_MetalIngot_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Wood_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Thatch_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Obsidian_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_AnglerGel_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_BlackPearl_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Silicon_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Berry_Narcoberry_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Berry_Amarberry_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Berry_Azulberry_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Berry_Mejoberry_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Berry_Stimberry_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Berry_Tintoberry_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Fibers_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Stone_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Charcoal_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Hide_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Keratin_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Sap_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Crystal_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Electronics_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Flint_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Polymer_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Polymer_Organic_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Gunpowder_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Oil_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Pelt_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_RawSalt_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Sand_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Fertilizer_Compost_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Sparkpowder_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_SpoiledMeat_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_ChitinPaste_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Sulfur_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Gasoline_C",Quantity=(MaxItemQuantity=10000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_SubstrateAbsorbent_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Propellant_C",Quantity=(MaxItemQuantity=1000.0, bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_CookedMeat_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_CookedMeat_Fish_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawPrimeMeat_Fish_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_CookedPrimeMeat_Fish_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawMutton_Fish_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_CookedPrimeMeat_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawPrimeMeat_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_DinoPoopSmall_C", Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_DinoPoopMedium_C", Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_DinoPoopMassive_C", Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_DinoPoopLarge_C", Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_RawMutton_C", Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemAmmo_AdvancedRifleBullet_C", Quantity=(MaxItemQuantity=10000,bIgnoreMultiplier=True))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Element_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_ElementDust_C",Quantity=(MaxItemQuantity=10000,bIgnoreMultiplier=true))
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_ElementShard_C",Quantity=(MaxItemQuantity=10000,bIgnoreMultiplier=true))
BaseHexagonRewardMultiplier=1
HexagonCostMultiplier=1
bHardLimitTurretsInRange=true
bShowCreativeMode=false
bDisableLootCrates=false
bDisablePhotoMode=false
PhotoModeRangeLimit=3600
bFlyerPlatformAllowUnalignedDinoBasing=false
bAutoPvEUseSystemTime=false
OverrideMaxExperiencePointsPlayer=0
OverrideMaxExperiencePointsDino=0

; Specific Harvest Multipliers
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ElementDust_C",Multiplier=7.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_BlackPearl_C",Multiplier=3.0)

;--- BOSS ELEMENT REWARDS (3x BASE) ---
; Island & Scorched
ConfigOverrideElementRewardFromBoss=(BossClassString="SpiderL_Character_BP_Gamma_C", ElementAmount=60)
ConfigOverrideElementRewardFromBoss=(BossClassString="SpiderL_Character_BP_Beta_C", ElementAmount=168)
ConfigOverrideElementRewardFromBoss=(BossClassString="SpiderL_Character_BP_Alpha_C", ElementAmount=444)
ConfigOverrideElementRewardFromBoss=(BossClassString="Gorilla_Character_BP_Gamma_C", ElementAmount=120)
ConfigOverrideElementRewardFromBoss=(BossClassString="Gorilla_Character_BP_Beta_C", ElementAmount=330)
ConfigOverrideElementRewardFromBoss=(BossClassString="Gorilla_Character_BP_Alpha_C", ElementAmount=660)
ConfigOverrideElementRewardFromBoss=(BossClassString="Dragon_Character_BP_Gamma_C", ElementAmount=240)
ConfigOverrideElementRewardFromBoss=(BossClassString="Dragon_Character_BP_Beta_C", ElementAmount=660)
ConfigOverrideElementRewardFromBoss=(BossClassString="Dragon_Character_BP_Alpha_C", ElementAmount=1320)
ConfigOverrideElementRewardFromBoss=(BossClassString="Manticore_Character_BP_Gamma_C", ElementAmount=114)
ConfigOverrideElementRewardFromBoss=(BossClassString="Manticore_Character_BP_Beta_C", ElementAmount=405)
ConfigOverrideElementRewardFromBoss=(BossClassString="Manticore_Character_BP_Alpha_C", ElementAmount=855)

; The Center & Lost Colony & Underwater
ConfigOverrideElementRewardFromBoss=(BossClassString="ArtifactTier1_C", ElementAmount=180)
ConfigOverrideElementRewardFromBoss=(BossClassString="ArtifactTier2_C", ElementAmount=498)
ConfigOverrideElementRewardFromBoss=(BossClassString="ArtifactTier3_C", ElementAmount=1104)
ConfigOverrideElementRewardFromBoss=(BossClassString="LostKing_Character_BP_Gamma_C", ElementAmount=300)
ConfigOverrideElementRewardFromBoss=(BossClassString="LostKing_Character_BP_Beta_C", ElementAmount=600)
ConfigOverrideElementRewardFromBoss=(BossClassString="LostKing_Character_BP_Alpha_C", ElementAmount=1500)
ConfigOverrideElementRewardFromBoss=(BossClassString="Moeder_Character_BP_Gamma_C", ElementAmount=165)
ConfigOverrideElementRewardFromBoss=(BossClassString="Moeder_Character_BP_Beta_C", ElementAmount=420)
ConfigOverrideElementRewardFromBoss=(BossClassString="Moeder_Character_BP_Alpha_C", ElementAmount=864)

; Aberration & Extinction
ConfigOverrideElementRewardFromBoss=(BossClassString="Rockwell_Character_BP_Gamma_C", ElementAmount=120)
ConfigOverrideElementRewardFromBoss=(BossClassString="Rockwell_Character_BP_Beta_C", ElementAmount=300)
ConfigOverrideElementRewardFromBoss=(BossClassString="Rockwell_Character_BP_Alpha_C", ElementAmount=660)
ConfigOverrideElementRewardFromBoss=(BossClassString="ForestTitan_Character_BP_C", ElementAmount=300)
ConfigOverrideElementRewardFromBoss=(BossClassString="IceTitan_Character_BP_C", ElementAmount=300)
ConfigOverrideElementRewardFromBoss=(BossClassString="DesertTitan_Character_BP_C", ElementAmount=300)
ConfigOverrideElementRewardFromBoss=(BossClassString="KingTitan_Character_BP_Gamma_C", ElementAmount=120)
ConfigOverrideElementRewardFromBoss=(BossClassString="KingTitan_Character_BP_Beta_C", ElementAmount=240)
ConfigOverrideElementRewardFromBoss=(BossClassString="KingTitan_Character_BP_Alpha_C", ElementAmount=1500)